### ISSUE TITLE
User Crime Report Management

### ISSUE THREAD

**Issue by mckainbadger** [jrs-coding-school/summer-2023-group-project#44]
As a user viewing the list of my reports, I want to see details about the report such as: severity of crime, type of crime, location, time/date, description, ongoing status, link to official report, so that I know what needs to be modified
AC
- [x] Display a list of the user's reports with summary information such as the severity of the crime, type of crime, location, and date/time.
- [x] The user should have a dashboard or page where they can view a list of their reports.
- [ ] The user should be able to click on a report item to view its full details, including the description and ongoing status.
- [ ] If available, the report details should include a link to the official report related to the crime.
- [ ] Allow the user to scroll through their reports and view the details for each report.

As a user who has reported a crime, I want to be able to delete my previous reports so that it is no longer displayed on the map
AC
- [ ] The user should have access to a "My Reports" section or a similar feature that displays their submitted reports.
- [ ] Each report in the "My Reports" section should have a "Delete" button or icon.
- [ ] When the user clicks the "Delete" button for a report, a confirmation prompt should appear to confirm their action.
- [ ] If the user confirms the deletion, the report should be permanently removed from the system and should no longer be displayed on the map or in the user's list of reports.

As a user who has reported a crime, I want to be able to edit my previous reports, so that if I make a mistake I can change the data displayed

AC:

- [ ] The user should have access to a "My Reports" section or a similar feature that displays their submitted reports.
- [ ] Each report in the "My Reports" section should have an "Edit" button or icon.
- [ ] When the user clicks the "Edit" button for a report, a form should be displayed with pre-filled data from the existing report.
- [ ] The user should be able to modify any field in the report, including severity, type, location, date, time, description, and ongoing status.
- [ ] Upon submitting the edited report, the changes should be saved to the database and reflected in the user's list of reports and on the map.

**Comment by Amin-JRS** [comment]
Includes #39 and #41.

This feature is similar to the admin panel
